/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AutoRenumbering
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// node_modules/async-mutex/index.mjs
var E_TIMEOUT = new Error("timeout while waiting for mutex to become available");
var E_ALREADY_LOCKED = new Error("mutex already locked");
var E_CANCELED = new Error("request for lock canceled");
var __awaiter$2 = function(thisArg, _arguments, P, generator) {
  function adopt(value) {
    return value instanceof P ? value : new P(function(resolve) {
      resolve(value);
    });
  }
  return new (P || (P = Promise))(function(resolve, reject) {
    function fulfilled(value) {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    }
    function rejected(value) {
      try {
        step(generator["throw"](value));
      } catch (e) {
        reject(e);
      }
    }
    function step(result) {
      result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected);
    }
    step((generator = generator.apply(thisArg, _arguments || [])).next());
  });
};
var Semaphore = class {
  constructor(_value, _cancelError = E_CANCELED) {
    this._value = _value;
    this._cancelError = _cancelError;
    this._queue = [];
    this._weightedWaiters = [];
  }
  acquire(weight = 1, priority = 0) {
    if (weight <= 0)
      throw new Error(`invalid weight ${weight}: must be positive`);
    return new Promise((resolve, reject) => {
      const task = { resolve, reject, weight, priority };
      const i = findIndexFromEnd(this._queue, (other) => priority <= other.priority);
      if (i === -1 && weight <= this._value) {
        this._dispatchItem(task);
      } else {
        this._queue.splice(i + 1, 0, task);
      }
    });
  }
  runExclusive(callback_1) {
    return __awaiter$2(this, arguments, void 0, function* (callback, weight = 1, priority = 0) {
      const [value, release] = yield this.acquire(weight, priority);
      try {
        return yield callback(value);
      } finally {
        release();
      }
    });
  }
  waitForUnlock(weight = 1, priority = 0) {
    if (weight <= 0)
      throw new Error(`invalid weight ${weight}: must be positive`);
    if (this._couldLockImmediately(weight, priority)) {
      return Promise.resolve();
    } else {
      return new Promise((resolve) => {
        if (!this._weightedWaiters[weight - 1])
          this._weightedWaiters[weight - 1] = [];
        insertSorted(this._weightedWaiters[weight - 1], { resolve, priority });
      });
    }
  }
  isLocked() {
    return this._value <= 0;
  }
  getValue() {
    return this._value;
  }
  setValue(value) {
    this._value = value;
    this._dispatchQueue();
  }
  release(weight = 1) {
    if (weight <= 0)
      throw new Error(`invalid weight ${weight}: must be positive`);
    this._value += weight;
    this._dispatchQueue();
  }
  cancel() {
    this._queue.forEach((entry) => entry.reject(this._cancelError));
    this._queue = [];
  }
  _dispatchQueue() {
    this._drainUnlockWaiters();
    while (this._queue.length > 0 && this._queue[0].weight <= this._value) {
      this._dispatchItem(this._queue.shift());
      this._drainUnlockWaiters();
    }
  }
  _dispatchItem(item) {
    const previousValue = this._value;
    this._value -= item.weight;
    item.resolve([previousValue, this._newReleaser(item.weight)]);
  }
  _newReleaser(weight) {
    let called = false;
    return () => {
      if (called)
        return;
      called = true;
      this.release(weight);
    };
  }
  _drainUnlockWaiters() {
    if (this._queue.length === 0) {
      for (let weight = this._value; weight > 0; weight--) {
        const waiters = this._weightedWaiters[weight - 1];
        if (!waiters)
          continue;
        waiters.forEach((waiter) => waiter.resolve());
        this._weightedWaiters[weight - 1] = [];
      }
    } else {
      const queuedPriority = this._queue[0].priority;
      for (let weight = this._value; weight > 0; weight--) {
        const waiters = this._weightedWaiters[weight - 1];
        if (!waiters)
          continue;
        const i = waiters.findIndex((waiter) => waiter.priority <= queuedPriority);
        (i === -1 ? waiters : waiters.splice(0, i)).forEach((waiter) => waiter.resolve());
      }
    }
  }
  _couldLockImmediately(weight, priority) {
    return (this._queue.length === 0 || this._queue[0].priority < priority) && weight <= this._value;
  }
};
function insertSorted(a, v) {
  const i = findIndexFromEnd(a, (other) => v.priority <= other.priority);
  a.splice(i + 1, 0, v);
}
function findIndexFromEnd(a, predicate) {
  for (let i = a.length - 1; i >= 0; i--) {
    if (predicate(a[i])) {
      return i;
    }
  }
  return -1;
}
var __awaiter$1 = function(thisArg, _arguments, P, generator) {
  function adopt(value) {
    return value instanceof P ? value : new P(function(resolve) {
      resolve(value);
    });
  }
  return new (P || (P = Promise))(function(resolve, reject) {
    function fulfilled(value) {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    }
    function rejected(value) {
      try {
        step(generator["throw"](value));
      } catch (e) {
        reject(e);
      }
    }
    function step(result) {
      result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected);
    }
    step((generator = generator.apply(thisArg, _arguments || [])).next());
  });
};
var Mutex = class {
  constructor(cancelError) {
    this._semaphore = new Semaphore(1, cancelError);
  }
  acquire() {
    return __awaiter$1(this, arguments, void 0, function* (priority = 0) {
      const [, releaser] = yield this._semaphore.acquire(1, priority);
      return releaser;
    });
  }
  runExclusive(callback, priority = 0) {
    return this._semaphore.runExclusive(() => callback(), 1, priority);
  }
  isLocked() {
    return this._semaphore.isLocked();
  }
  waitForUnlock(priority = 0) {
    return this._semaphore.waitForUnlock(1, priority);
  }
  release() {
    if (this._semaphore.isLocked())
      this._semaphore.release();
  }
  cancel() {
    return this._semaphore.cancel();
  }
};

// src/SettingsManager.ts
var DEFAULT_SETTINGS = {
  liveUpdate: true,
  smartPaste: true,
  indentSize: 4
};
var SettingsManager = class {
  constructor() {
    this.settings = DEFAULT_SETTINGS;
  }
  static getInstance() {
    if (!SettingsManager.instance) {
      SettingsManager.instance = new SettingsManager();
    }
    return SettingsManager.instance;
  }
  setSettings(settings) {
    this.settings = settings;
  }
  getSettings() {
    return this.settings;
  }
  setLiveUpdate(value) {
    this.settings.liveUpdate = value;
  }
  setSmartPaste(value) {
    this.settings.smartPaste = value;
  }
  setIndentSize(value) {
    this.settings.indentSize = value;
  }
};

// src/utils.ts
function getLineInfo(line) {
  const length = line.length;
  let index = 0;
  let numOfSpaceIndents = 0;
  const settingsManager = SettingsManager.getInstance();
  const sett = settingsManager.getSettings();
  const indentSize = sett.indentSize;
  while (index < length && (line[index] === " " || line[index] === "	")) {
    numOfSpaceIndents += line[index] === " " ? 1 : indentSize;
    index++;
  }
  const numOfSpaceChars = index;
  while (index < length && "0".charCodeAt(0) <= line.charCodeAt(index) && line.charCodeAt(index) <= "9".charCodeAt(0))
    index++;
  if (line[index] !== "." || line[index + 1] !== " ") {
    return {
      numOfSpaceChars,
      spaceIndent: numOfSpaceIndents,
      number: void 0,
      textIndex: void 0
    };
  }
  const number = parseInt(line.slice(numOfSpaceChars, index));
  if (isNaN(number)) {
    return {
      numOfSpaceChars,
      spaceIndent: numOfSpaceIndents,
      number: void 0,
      textIndex: void 0
    };
  }
  return { numOfSpaceChars, spaceIndent: numOfSpaceIndents, number, textIndex: index + 2 };
}
function getListStart(editor, currLineIndex) {
  if (currLineIndex < 0 || editor.lastLine() < currLineIndex) {
    return void 0;
  }
  const currInfo = getLineInfo(editor.getLine(currLineIndex));
  if (currInfo.number === void 0) {
    return void 0;
  }
  if (currLineIndex == 0)
    return 0;
  let prevIndex = currLineIndex - 1;
  while (0 <= prevIndex && getLineInfo(editor.getLine(prevIndex)).number !== void 0) {
    prevIndex--;
  }
  return prevIndex + 1;
}
function getLastListIndex(lines) {
  let index = void 0;
  for (let i = lines.length - 1; i >= 0; i--) {
    const info = getLineInfo(lines[i]);
    if (info.number === void 0) {
      break;
    }
    index = i;
  }
  return index;
}

// src/pasteHandler.ts
function handlePaste(editor, textFromClipboard) {
  var _a;
  const { anchor, head } = editor.listSelections()[0];
  const baseIndex = Math.min(anchor.line, head.line);
  let numOfLines;
  const settingsManager = SettingsManager.getInstance();
  const smartPaste = settingsManager.getSettings().smartPaste;
  if (smartPaste) {
    const afterPasteIndex = Math.max(anchor.line, head.line) + 1;
    const line = editor.getLine(afterPasteIndex);
    const info = getLineInfo(line);
    if (info.number !== void 0) {
      const retval = modifyText(textFromClipboard, info.number);
      textFromClipboard = (_a = retval.modifiedText) != null ? _a : textFromClipboard;
      numOfLines = retval.numOfLines;
    } else {
      numOfLines = countNewlines(textFromClipboard);
    }
  } else {
    numOfLines = countNewlines(textFromClipboard);
  }
  editor.replaceSelection(textFromClipboard);
  return { baseIndex, offset: numOfLines };
}
function countNewlines(text) {
  let count = 0;
  for (const char of text) {
    if (char === "\n") {
      count++;
    }
  }
  return count;
}
function modifyText(text, newNumber) {
  const lines = text.split("\n");
  const lineIndex = getLastListIndex(lines);
  if (lineIndex === void 0) {
    return { modifiedText: void 0, numOfLines: lines.length };
  }
  const targetLine = lines[lineIndex];
  const info = getLineInfo(targetLine);
  const newLine = targetLine.slice(0, info.numOfSpaceChars) + newNumber + ". " + targetLine.slice(info.textIndex);
  lines[lineIndex] = newLine;
  const modifiedText = lines.join("\n");
  return { modifiedText, numOfLines: lines.length };
}

// src/registerCommands.ts
function registerCommands(plugin) {
  plugin.addCommand({
    id: "1-cursor",
    name: "At cursor position",
    editorCallback: (editor) => {
      plugin.setIsProcessing(true);
      plugin.getRenumberer().listAtCursor(editor, plugin.getChanges());
      plugin.getRenumberer().applyChangesToEditor(editor, plugin.getChanges());
      plugin.setIsProcessing(false);
    }
  });
  plugin.addCommand({
    id: "2-selection",
    name: "All selected numbered lists",
    editorCallback: (editor) => {
      const { anchor, head } = editor.listSelections()[0];
      const startLine = Math.min(anchor.line, head.line);
      const endLine = Math.max(anchor.line, head.line);
      plugin.getRenumberer().allListsInRange(editor, plugin.getChanges(), startLine, endLine);
      plugin.getRenumberer().applyChangesToEditor(editor, plugin.getChanges());
    }
  });
  plugin.addCommand({
    id: "3-note",
    name: "All numbered lists in the entire note",
    editorCallback: (editor) => {
      plugin.getRenumberer().allListsInRange(editor, plugin.getChanges(), 0, editor.lastLine());
      plugin.getRenumberer().applyChangesToEditor(editor, plugin.getChanges());
    }
  });
}

// src/IndentTracker.ts
var IndentTracker = class {
  // builds the stack from the beginning of a numbered list, to the current line
  constructor(editor, currLine) {
    this.stack = [];
    if (currLine < 0)
      return;
    const currSpaceOffset = getLineInfo(editor.getLine(currLine)).spaceIndent;
    let prevIndex = currLine - 1;
    let prevSpaceOffset = void 0;
    for (; prevIndex >= 0; prevIndex--) {
      prevSpaceOffset = getLineInfo(editor.getLine(prevIndex)).spaceIndent;
      if (prevSpaceOffset <= currSpaceOffset) {
        break;
      }
    }
    if (prevSpaceOffset && prevSpaceOffset > currSpaceOffset) {
      return;
    }
    for (let i = Math.max(prevIndex, 0); i < currLine; i++) {
      this.insert(editor.getLine(i));
    }
    this.lastStackIndex = this.stack.length - 1;
  }
  get() {
    return this.stack;
  }
  // inserts a line to the stack, ensuring its the last one each time. items in higher indices do not affect lower ones.
  insert(textLine) {
    const info = getLineInfo(textLine);
    this.lastStackIndex = info.spaceIndent;
    this.stack[this.lastStackIndex] = info.number;
    this.stack.length = this.lastStackIndex + 1;
  }
};

// src/Renumberer.ts
var Renumberer = class {
  constructor() {
    // renumbers the list at cursor location from start to end
    this.listAtCursor = (editor, changes) => {
      const { anchor, head } = editor.listSelections()[0];
      const currLine = Math.min(anchor.line, head.line);
      changes.push(...this.renumberBlock(editor, currLine).changes);
      this.applyChangesToEditor(editor, changes);
    };
    // renumbers all numbered lists in specified range
    this.allListsInRange = (editor, changes, currLine, end) => {
      while (currLine <= end) {
        const line = editor.getLine(currLine);
        if (line) {
          const { number } = getLineInfo(line);
          if (number) {
            const newChanges = this.renumberBlock(editor, currLine);
            if (newChanges.endIndex !== void 0) {
              changes.push(...newChanges.changes);
              currLine = newChanges.endIndex;
            }
          }
        }
        currLine++;
      }
      if (changes.length > 0) {
        this.applyChangesToEditor(editor, changes);
      }
    };
  }
  // updates a numbered list from start to end
  renumberBlock(editor, currLine) {
    const startIndex = getListStart(editor, currLine);
    if (startIndex === void 0) {
      return { changes: [], endIndex: void 0 };
    }
    return this.generateChanges(editor, startIndex);
  }
  // updates a numbered list from the current line, to the first correctly number line.
  renumberLocally(editor, startIndex) {
    let currInfo = getLineInfo(editor.getLine(startIndex));
    let prevInfo = void 0;
    if (currInfo.number === void 0) {
      startIndex++;
      prevInfo = currInfo;
      currInfo = getLineInfo(editor.getLine(startIndex));
    }
    if (currInfo.number === void 0) {
      startIndex++;
      return { changes: [], endIndex: startIndex };
    }
    if (startIndex <= 0) {
      return startIndex === editor.lastLine() ? { changes: [], endIndex: startIndex } : this.generateChanges(editor, startIndex + 1, true);
    }
    if (prevInfo !== void 0 && !prevInfo.number && prevInfo.numOfSpaceChars < currInfo.numOfSpaceChars) {
      startIndex++;
    }
    return this.generateChanges(editor, startIndex, true);
  }
  // performs the calculation itself
  generateChanges(editor, currLine, isLocal = false) {
    const changes = [];
    const indentTracker = new IndentTracker(editor, currLine);
    let firstChange = true;
    let prevSpaceIndent = getLineInfo(editor.getLine(currLine - 1)).spaceIndent;
    const endOfList = editor.lastLine() + 1;
    for (; currLine < endOfList; currLine++) {
      const text = editor.getLine(currLine);
      const { spaceIndent, numOfSpaceChars, number: currNum, textIndex } = getLineInfo(editor.getLine(currLine));
      if (currNum === void 0) {
        firstChange = false;
        if (prevSpaceIndent < spaceIndent) {
          indentTracker.insert(text);
          continue;
        }
        break;
      }
      const previousNum = indentTracker.get()[spaceIndent];
      const expectedNum = previousNum === void 0 ? void 0 : previousNum + 1;
      let newText = text;
      if (expectedNum !== void 0) {
        const isValidIndent = spaceIndent <= indentTracker.get().length;
        if (expectedNum !== currNum && isValidIndent) {
          newText = text.slice(0, numOfSpaceChars) + expectedNum + ". " + text.slice(textIndex);
          changes.push({
            from: { line: currLine, ch: 0 },
            to: { line: currLine, ch: text.length },
            text: newText
          });
        } else if (isLocal && !firstChange && spaceIndent === 0) {
          break;
        }
      }
      indentTracker.insert(newText);
      prevSpaceIndent = spaceIndent;
      firstChange = false;
    }
    return { changes, endIndex: currLine - 1 };
  }
  applyChangesToEditor(editor, changes) {
    const changesApplied = changes.length > 0;
    if (changesApplied) {
      editor.transaction({ changes });
    }
    changes.splice(0, changes.length);
    return changesApplied;
  }
};

// src/SettingsTab.ts
var import_obsidian = require("obsidian");
var AutoRenumberingSettings = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.settingsManager = SettingsManager.getInstance();
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Live update").setDesc("Automatically update numbered lists as changes are made. Does not support Vim.").addToggle(
      (toggle) => toggle.setValue(this.settingsManager.getSettings().liveUpdate).onChange(async (value) => {
        this.settingsManager.setLiveUpdate(value);
        await this.plugin.saveSettings();
        smartPasteToggleEl.classList.toggle("smart-paste-toggle", value);
        smartPasteToggleEl.classList.toggle("smart-paste-toggle-disabled", !value);
      })
    );
    const smartPasteSetting = new import_obsidian.Setting(containerEl).setName("Smart paste").setDesc("Pasting keeps the sequencing consistent with the original numbered list.").addToggle(
      (toggle) => toggle.setValue(this.settingsManager.getSettings().smartPaste).onChange(async (value) => {
        this.settingsManager.setSmartPaste(value);
        await this.plugin.saveSettings();
      })
    );
    const smartPasteToggleEl = smartPasteSetting.settingEl;
    const isLiveUpdateEnabled = this.settingsManager.getSettings().liveUpdate;
    smartPasteToggleEl.classList.add(isLiveUpdateEnabled ? "smart-paste-toggle" : "smart-paste-toggle-disabled");
    new import_obsidian.Setting(containerEl).setName("Tab indent size").setDesc(
      "Set the indent size to the same size as in the editor's settings. Can be found under: Options > Editor > Tab indent size."
    ).addSlider((slider) => {
      slider.setValue(this.settingsManager.getSettings().indentSize).setLimits(2, 8, 1).setDynamicTooltip().onChange(async (value) => {
        this.settingsManager.setIndentSize(value);
        await this.plugin.saveSettings();
      });
    });
  }
};

// main.ts
var mutex = new Mutex();
var AutoRenumbering = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.changes = [];
    this.isProccessing = false;
    this.blockChanges = false;
  }
  async onload() {
    await this.loadSettings();
    registerCommands(this);
    this.addSettingTab(new AutoRenumberingSettings(this.app, this));
    this.renumberer = new Renumberer();
    this.settingsManager = SettingsManager.getInstance();
    this.registerEvent(
      this.app.workspace.on("editor-change", (editor) => {
        if (this.settingsManager.getSettings().liveUpdate === false) {
          return;
        }
        if (!this.isProccessing) {
          this.isProccessing = true;
          setTimeout(() => {
            mutex.runExclusive(() => {
              if (this.blockChanges) {
                return;
              }
              this.blockChanges = true;
              const { anchor, head } = editor.listSelections()[0];
              const currLine = Math.min(anchor.line, head.line);
              this.changes.push(...this.renumberer.renumberLocally(editor, currLine).changes);
              this.renumberer.applyChangesToEditor(editor, this.changes);
            });
            this.isProccessing = false;
          }, 0);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-paste", (evt, editor) => {
        var _a;
        if (this.settingsManager.getSettings().liveUpdate === false) {
          return;
        }
        const clipboardContent = (_a = evt.clipboardData) == null ? void 0 : _a.getData("text");
        if (evt.defaultPrevented || !clipboardContent) {
          return;
        }
        evt.preventDefault();
        mutex.runExclusive(() => {
          this.blockChanges = true;
          const { baseIndex, offset } = handlePaste(editor, clipboardContent);
          this.renumberer.allListsInRange(editor, this.changes, baseIndex, baseIndex + offset);
          this.renumberer.applyChangesToEditor(editor, this.changes);
        });
      })
    );
    this.handleKeystrokeBound = this.handleKeystroke.bind(this);
    window.addEventListener("keydown", this.handleKeystrokeBound);
  }
  handleKeystroke(event) {
    mutex.runExclusive(() => {
      this.blockChanges = event.ctrlKey || event.metaKey || event.altKey;
    });
  }
  async onunload() {
    window.removeEventListener("keydown", this.handleKeystrokeBound);
  }
  async loadSettings() {
    const settingsManager = SettingsManager.getInstance();
    settingsManager.setSettings(Object.assign({}, DEFAULT_SETTINGS, await this.loadData()));
  }
  async saveSettings() {
    const settingsManager = SettingsManager.getInstance();
    await this.saveData(settingsManager.getSettings());
  }
  getRenumberer() {
    return this.renumberer;
  }
  getIsProcessing() {
    return this.isProccessing;
  }
  getChanges() {
    return this.changes;
  }
  setIsProcessing(value) {
    this.isProccessing = value;
  }
};


/* nosourcemap */